### ISSUE TITLE
What is RLS doing when I haven't touched the window in many minutes?

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rls-vscode#504]
I have a Rust project opened, but there isn't a single file open. VS Code isn't even visible on my screen, and I haven't touched anything in ~15 minutes or so. Despite this, RLS uses a full CPU core at max as well as 12% of my memory (just under 1 GB). I'm _very_ curious what on earth RLS is doing, since it certainly _shouldn't_ be doing anything. The RAM makes sense to an extent, but the CPU usage doesn't at all.

If someone can provide instructions on how to get a stack trace (or whatever else is relevant), I'd be happy to provide such.

**Comment by sntdevco** [comment]
You _probably_ have a lot of dependencies which RLS is building in the background to provide better code completion. It's nothing to worry about and it's a pretty common thing

**Comment by jhpratt** [comment]
The icon in the corner didn't show anything was happening, and this occurs well after anything has been changed. I don't suspect that's the cause, it's not like we're just starting up.

**Comment by sntdevco** [comment]
> The icon in the corner didn't show anything was happening, and this occurs well after anything has been changed. I don't suspect that's the cause, it's not like we're just starting up.

Can you reproduce it?

**Comment by jhpratt** [comment]
Like I said in the original post, the issue seems to occur without any input or recent changes, given that I hadn't used VS Code in quite a few minutes (it was still open the whole time).

Of note, though, I _have not_ experienced this recently. I'm not sure if it was a transient issue in RLS that is now resolved. If I don't experience it for a while, I'll just close this issue as resolved.

**Comment by jhpratt** [comment]
Closing as I haven't run into this in quite a while. If anyone has this issue again, just respond and I'll re-open.

**Comment by Southclaws** [comment]
Still getting this, been running for about 10 minutes, yet `cargo build`/`cargo check` runs fine. No category for RLS in the Output dropdown so I can't really debug it.

This was working like a month ago, how is it broken again?
